name: "Custom env vars"

on: ['push']

env: 
 DAY_OF_WEEK: Monday

jobs: 
 greetings_job:
  runs-on: ubuntu-latest
  env:
    Greeting: Hello
  steps:
   - name: "Say Hello Mona It´s Monday"
     if: ${{env.DAY_OF_WEEK == 'Monday'}}
     run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK"
     env:
      First_Name: Mona
 setup-and-use-env:
    runs-on: ubuntu-latest
    steps:
     - name: Set dynamic environment variable
       run: |
         # Using workflow command to set an environment variable
         echo "DYNAMIC_VAR=Hello from Github Actions" >> $GITHUB_ENV
     - name: Use the environment variable
       run: |
         # Using the environment variable in the next step
         echo "The value of DYNAMIC_VAR is: $DYNAMIC_VAR"