name: "Secrets example"

on: ['push']

jobs:
 job1:
    runs-on: ubuntu-latest
    steps:
     - name: Run a script using secret
       run: |
         echo "Using API key: $SECRET"
       env:
         SECRET: ${{secrets.MY_SECRET}}

