name: "Wokflow Commands"

on:
 push:
  branches:
    - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
     - name: "group logging"
       run: |
        echo "::group:: My group message"
        echo "Message 1"
        echo "Message 2"
        echo "::endgroup::"
     - name: "Assigns hello value to GITHUB_ENV"
       run: |
        echo "MY_VAL=hello" >> $GITHUB_ENV
     - name: "Prints value from var"
       run: |
        echo $MY_VAL
        


